/**
 * Liste ISO 4217 (codes devise à trois lettres) avec noms français —
 * norme externe réelle, jamais une donnée inventée (même raisonnement
 * que `countries.ts`, Lot 7). Triée par nom français.
 */
export type Currency = { code: string; name: string };

export const CURRENCIES: Currency[] = [
    { code: 'ZAR', name: 'Rand sud-africain' },
    { code: 'AED', name: 'Dirham des Émirats arabes unis' },
    { code: 'AFN', name: 'Afghani afghan' },
    { code: 'ALL', name: 'Lek albanais' },
    { code: 'AMD', name: 'Dram arménien' },
    { code: 'AOA', name: 'Kwanza angolais' },
    { code: 'ARS', name: 'Peso argentin' },
    { code: 'AUD', name: 'Dollar australien' },
    { code: 'AZN', name: 'Manat azerbaïdjanais' },
    { code: 'BDT', name: 'Taka bangladais' },
    { code: 'BGN', name: 'Lev bulgare' },
    { code: 'BHD', name: 'Dinar bahreïni' },
    { code: 'BIF', name: 'Franc burundais' },
    { code: 'BOB', name: 'Boliviano bolivien' },
    { code: 'BRL', name: 'Real brésilien' },
    { code: 'BWP', name: 'Pula botswanais' },
    { code: 'BYN', name: 'Rouble biélorusse' },
    { code: 'CAD', name: 'Dollar canadien' },
    { code: 'CDF', name: 'Franc congolais' },
    { code: 'CHF', name: 'Franc suisse' },
    { code: 'CLP', name: 'Peso chilien' },
    { code: 'CNY', name: 'Yuan chinois' },
    { code: 'COP', name: 'Peso colombien' },
    { code: 'CRC', name: 'Colón costaricien' },
    { code: 'CUP', name: 'Peso cubain' },
    { code: 'CVE', name: 'Escudo cap-verdien' },
    { code: 'CZK', name: 'Couronne tchèque' },
    { code: 'DJF', name: 'Franc djiboutien' },
    { code: 'DKK', name: 'Couronne danoise' },
    { code: 'DOP', name: 'Peso dominicain' },
    { code: 'DZD', name: 'Dinar algérien' },
    { code: 'EGP', name: 'Livre égyptienne' },
    { code: 'ERN', name: 'Nakfa érythréen' },
    { code: 'ETB', name: 'Birr éthiopien' },
    { code: 'EUR', name: 'Euro' },
    { code: 'FJD', name: 'Dollar fidjien' },
    { code: 'GBP', name: 'Livre sterling' },
    { code: 'GEL', name: 'Lari géorgien' },
    { code: 'GHS', name: 'Cedi ghanéen' },
    { code: 'GMD', name: 'Dalasi gambien' },
    { code: 'GNF', name: 'Franc guinéen' },
    { code: 'GTQ', name: 'Quetzal guatémaltèque' },
    { code: 'GYD', name: 'Dollar guyanien' },
    { code: 'HKD', name: 'Dollar de Hong Kong' },
    { code: 'HNL', name: 'Lempira hondurien' },
    { code: 'HTG', name: 'Gourde haïtienne' },
    { code: 'HUF', name: 'Forint hongrois' },
    { code: 'IDR', name: 'Roupie indonésienne' },
    { code: 'ILS', name: 'Shekel israélien' },
    { code: 'INR', name: 'Roupie indienne' },
    { code: 'IQD', name: 'Dinar irakien' },
    { code: 'IRR', name: 'Rial iranien' },
    { code: 'ISK', name: 'Couronne islandaise' },
    { code: 'JMD', name: 'Dollar jamaïcain' },
    { code: 'JOD', name: 'Dinar jordanien' },
    { code: 'JPY', name: 'Yen japonais' },
    { code: 'KES', name: 'Shilling kényan' },
    { code: 'KGS', name: 'Som kirghize' },
    { code: 'KHR', name: 'Riel cambodgien' },
    { code: 'KMF', name: 'Franc comorien' },
    { code: 'KRW', name: 'Won sud-coréen' },
    { code: 'KWD', name: 'Dinar koweïtien' },
    { code: 'KZT', name: 'Tenge kazakh' },
    { code: 'LAK', name: 'Kip laotien' },
    { code: 'LBP', name: 'Livre libanaise' },
    { code: 'LKR', name: 'Roupie srilankaise' },
    { code: 'LRD', name: 'Dollar libérien' },
    { code: 'LSL', name: 'Loti lesothan' },
    { code: 'LYD', name: 'Dinar libyen' },
    { code: 'MAD', name: 'Dirham marocain' },
    { code: 'MDL', name: 'Leu moldave' },
    { code: 'MGA', name: 'Ariary malgache' },
    { code: 'MKD', name: 'Denar macédonien' },
    { code: 'MMK', name: 'Kyat birman' },
    { code: 'MNT', name: 'Tugrik mongol' },
    { code: 'MRU', name: 'Ouguiya mauritanien' },
    { code: 'MUR', name: 'Roupie mauricienne' },
    { code: 'MVR', name: 'Rufiyaa maldivienne' },
    { code: 'MWK', name: 'Kwacha malawite' },
    { code: 'MXN', name: 'Peso mexicain' },
    { code: 'MYR', name: 'Ringgit malaisien' },
    { code: 'MZN', name: 'Metical mozambicain' },
    { code: 'NAD', name: 'Dollar namibien' },
    { code: 'NGN', name: 'Naira nigérian' },
    { code: 'NIO', name: 'Córdoba nicaraguayen' },
    { code: 'NOK', name: 'Couronne norvégienne' },
    { code: 'NPR', name: 'Roupie népalaise' },
    { code: 'NZD', name: 'Dollar néo-zélandais' },
    { code: 'OMR', name: 'Rial omanais' },
    { code: 'PAB', name: 'Balboa panaméen' },
    { code: 'PEN', name: 'Sol péruvien' },
    { code: 'PGK', name: 'Kina papouan-néo-guinéen' },
    { code: 'PHP', name: 'Peso philippin' },
    { code: 'PKR', name: 'Roupie pakistanaise' },
    { code: 'PLN', name: 'Zloty polonais' },
    { code: 'PYG', name: 'Guaraní paraguayen' },
    { code: 'QAR', name: 'Riyal qatari' },
    { code: 'RON', name: 'Leu roumain' },
    { code: 'RSD', name: 'Dinar serbe' },
    { code: 'RUB', name: 'Rouble russe' },
    { code: 'RWF', name: 'Franc rwandais' },
    { code: 'SAR', name: 'Riyal saoudien' },
    { code: 'SBD', name: 'Dollar des Îles Salomon' },
    { code: 'SCR', name: 'Roupie seychelloise' },
    { code: 'SDG', name: 'Livre soudanaise' },
    { code: 'SEK', name: 'Couronne suédoise' },
    { code: 'SGD', name: 'Dollar de Singapour' },
    { code: 'SLE', name: 'Leone sierra-léonais' },
    { code: 'SOS', name: 'Shilling somalien' },
    { code: 'SRD', name: 'Dollar surinamais' },
    { code: 'SSP', name: 'Livre sud-soudanaise' },
    { code: 'STN', name: 'Dobra santoméen' },
    { code: 'SYP', name: 'Livre syrienne' },
    { code: 'SZL', name: 'Lilangeni eswatinien' },
    { code: 'THB', name: 'Baht thaïlandais' },
    { code: 'TJS', name: 'Somoni tadjik' },
    { code: 'TMT', name: 'Manat turkmène' },
    { code: 'TND', name: 'Dinar tunisien' },
    { code: 'TRY', name: 'Livre turque' },
    { code: 'TTD', name: 'Dollar de Trinité-et-Tobago' },
    { code: 'TZS', name: 'Shilling tanzanien' },
    { code: 'UAH', name: 'Hryvnia ukrainienne' },
    { code: 'UGX', name: 'Shilling ougandais' },
    { code: 'USD', name: 'Dollar américain' },
    { code: 'UYU', name: 'Peso uruguayen' },
    { code: 'UZS', name: 'Sum ouzbek' },
    { code: 'VES', name: 'Bolívar vénézuélien' },
    { code: 'VND', name: 'Dông vietnamien' },
    { code: 'VUV', name: 'Vatu vanuatuan' },
    { code: 'WST', name: 'Tala samoan' },
    { code: 'XAF', name: 'Franc CFA (Afrique centrale)' },
    { code: 'XCD', name: 'Dollar des Caraïbes orientales' },
    { code: 'XOF', name: "Franc CFA (Afrique de l'Ouest)" },
    { code: 'YER', name: 'Rial yéménite' },
    { code: 'ZMW', name: 'Kwacha zambien' },
];
